// final url = 'http://localhost:3000/';
final url = 'https://todo-api-bgeh.onrender.com/';
final registration = url + "registeration";
final login = url + 'login';
final addtodo = url + 'store';
final getToDoList = url + 'stores';
final deleteTodo = url + 'delete';
final updateTodo = url + 'update';
final updateUser = url + 'user/update';